# Generated by Django 4.1.13 on 2024-10-20 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_aparecida', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passageiro',
            name='documento',
        ),
        migrations.RemoveField(
            model_name='passageiro',
            name='numero_acompanhante',
        ),
        migrations.RemoveField(
            model_name='passageiro',
            name='telefone',
        ),
        migrations.AddField(
            model_name='passageiro',
            name='cep',
            field=models.CharField(default='00000000', max_length=8),
        ),
        migrations.AddField(
            model_name='passageiro',
            name='cpf',
            field=models.CharField(default='00000000000', max_length=11, unique=True),
        ),
        migrations.AddField(
            model_name='passageiro',
            name='logradouro',
            field=models.CharField(default='Sem Logradouro', max_length=255),
        ),
        migrations.AddField(
            model_name='passageiro',
            name='numero',
            field=models.CharField(default='0', max_length=10),
        ),
        migrations.AddField(
            model_name='passageiro',
            name='rg',
            field=models.CharField(default='RG Padrão', max_length=50, unique=True),
        ),
        migrations.AddField(
            model_name='passageiro',
            name='tipo_usuario',
            field=models.CharField(default='gabryel', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='passageiro',
            name='email',
            field=models.EmailField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='passageiro',
            name='nome',
            field=models.CharField(max_length=50),
        ),
    ]
