# Generated by Django 4.1.13 on 2024-10-22 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_aparecida', '0002_remove_passageiro_documento_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='passageiro',
            old_name='numero',
            new_name='telefone',
        ),
        migrations.AlterField(
            model_name='passageiro',
            name='cpf',
            field=models.CharField(default='00000000000', max_length=18, unique=True),
        ),
        migrations.AlterField(
            model_name='passageiro',
            name='nome',
            field=models.CharField(default='sem nome', max_length=50),
        ),
    ]
