# Generated by Django 4.1.13 on 2024-10-22 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_aparecida', '0003_rename_numero_passageiro_telefone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passageiro',
            name='telefone',
            field=models.CharField(default='0', max_length=11),
        ),
    ]
