# Generated by Django 4.1.13 on 2024-10-22 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_aparecida', '0004_alter_passageiro_telefone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passageiro',
            name='nome',
            field=models.CharField(default='sem nome', max_length=50, unique=True),
        ),
    ]
