# Generated by Django 4.1.13 on 2024-10-22 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_aparecida', '0005_alter_passageiro_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passageiro',
            name='cep',
            field=models.CharField(default='00000000', max_length=11),
        ),
        migrations.AlterField(
            model_name='passageiro',
            name='nome',
            field=models.CharField(default='sem nome', max_length=50),
        ),
    ]
