# Generated by Django 4.1.13 on 2024-10-22 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_aparecida', '0006_alter_passageiro_cep_alter_passageiro_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passageiro',
            name='cep',
            field=models.CharField(default='00000000', max_length=8),
        ),
        migrations.AlterField(
            model_name='passageiro',
            name='cpf',
            field=models.CharField(default='00000000000', max_length=11, unique=True),
        ),
        migrations.AlterField(
            model_name='passageiro',
            name='telefone',
            field=models.CharField(default='0', max_length=10),
        ),
    ]
