# Generated by Django 4.1.13 on 2024-10-22 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_aparecida', '0008_alter_passageiro_cep_alter_passageiro_cpf_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passageiro',
            name='nome',
        ),
        migrations.AlterField(
            model_name='passageiro',
            name='username',
            field=models.CharField(default='sem nome', max_length=50, unique=True),
        ),
    ]
